apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webcolor
  name: webcolor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcolor
  strategy: {}
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
      - image: robertsilvatech/flask-color
        name: flask-color
        ports:
          - containerPort: 5000
status: {}
